# Generated by Django 4.2.8 on 2023-12-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
